# Generated by Django 5.1.4 on 2025-01-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DistrictData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("district", models.CharField(max_length=100)),
                ("sewage_gap_mld", models.FloatField()),
                ("water_quality_index", models.FloatField()),
                ("mean_temperature_celsius", models.FloatField()),
                ("mean_rainfall_mm", models.FloatField()),
                ("gddp_at_current_price_in_crore", models.FloatField()),
                ("number_of_tourists", models.FloatField()),
                ("number_of_asi_sites", models.FloatField()),
            ],
        ),
    ]
